config/routes.rb
Web25c::Application.routes.draw do
  
  # root :to => 'home#index'
  root :to => 'home#index'
  
  match 'coming_soon' => 'home#coming_soon', :as => :coming_soon
  
  # temporary demo page
  match 'demo' => 'home#demo'

  match 'auth/dwolla/callback' => 'home/payout#index', :as => :dwolla_auth_callback
  
  match 'sign-up' => 'users#new', :via => :get, :as => :register
  match 'sign-up' => 'users#create', :via => :post

  match 'sign-in' => 'sessions#new', :as => :sign_in, :via => :get
  match 'sign-in' => 'sessions#create', :via => :post
  match 'sign-out' => 'sessions#destroy', :as => :sign_out
  match 'request-password' => 'sessions#request_password', :as => :request_password
  match 'reset-password/:id' => 'sessions#reset_password', :as => :reset_password
  match 'auth/:provider/callback' => 'sessions#create'
  
  match 'widget/sign-in' => 'sessions#widget_new', :as => :widget_sign_in, :via => :get
  
  match 'about' => 'home#about', :as => :about
  match 'faq' => 'home#faq', :as => :faq
  match 'terms' => 'home#terms', :as => :terms
  match 'privacy' => 'home#privacy', :as => :privacy
  
  match 'blog/header' => 'home#blog_header', :as => :blog_header
  match 'blog/footer' => 'home#blog_footer', :as => :blog_footer
  
  # endpoints for Facebook Open Graph links
  match 'notes/:uuid' => 'open_graph#note', :as => :note
  match 'webpages/:uuid' => 'open_graph#webpage', :as => :webpage
  
  resources :i, :controller => 'invites', :as => 'invites', :only => [ :index, :show, :update ]
  
  namespace :tipper do
  
    # Dashboard
    match '' => 'dashboard#index', :as => :dashboard
    match 'cancel' => 'dashboard#cancel_click', :as => :cancel_click, :via => :delete
    
    # Buy Points
    match 'points' => 'points#index', :as => :points
    match 'points/checkout' => 'points#checkout', :as => :points_checkout
    match 'points/remove-card' => 'points#remove_card', :as => :points_remove_card
    
    # Payment
    match 'payment' => 'payment#index', :as => :payment
    match 'tip_register' => 'payment#tip_register', :as => :tip_register
    match 'site_register' => 'payment#site_register', :as => :site_register
    match 'payment/success' => 'payment#payment_success', :as => :payment_success
    match 'payment/failure' => 'payment#payment_failure', :as => :payment_failure
    match 'payment/dwolla'  => 'payment#payment_dwolla', :as => :payment_dwolla
    match 'create_payment' => 'payment#create_payment', :as => :create_payment, :via => :post
    
    # Account
    match 'account' => 'account#edit', :as => :account, :via => :get
    
  end
  
  namespace :publisher do
    # Dashboard
    root :to => 'dashboard#index', :as => :dashboard
    match 'request_payout' => 'dashboard#request_payout'
    match 'submit_request' =>  'dashboard#submit_request', :as => :submit_request
    # Widgets
    resources :widgets, :as => :buttons, :except => [ :new, :edit ]
    # Account
    resource :account, :as => :user, :only => [ :show, :update ]
    
    # Revenue Sharing
    match 'share_email' => 'widgets#share_email', :as => :share_email, :via => :put
    match 'cancel_email' => 'widgets#cancel_email', :as => :cancel_email, :via => :delete
    match 'stop_share' => 'widgets#stop_share', :as => :stop_share, :via => :delete    
  end
  
  namespace :admin do
    resources :users, :except => [ :new, :create ]
    match '' => 'dashboard#index', :as => :dashboard
    match 'process_payment' => 'dashboard#process_payment', :as => :process_payment, :via => :post
    match 'test' => 'dashboard#test', :as => :test
  end
  
  # catch-all 404 page for unknown routes
  match '*a' => 'home#not_found', :as => :not_found

end

app/models/button.rb
class Button < ActiveRecord::Base
  WIDGET_TYPES = %w(fan_belt testimonials)
    
  belongs_to :user
  has_many :clicks
  has_many :invites
    
  attr_accessible :title, :website_url, :description, :pledge_message, :widget_type, :additional_parameters
  
  serialize :share_users, JSON  
  serialize :additional_parameters, JSON
  
  validates :title, :presence => true
  validates :website_url, :presence => true
  validates :widget_type, :inclusion => { :in => WIDGET_TYPES }
    
  before_create :generate_uuid
    
  def to_param
    self.uuid
  end
  
  def share_invite(email, amount)
    if not email.blank? and amount.to_i > 0
      self.invites.create(:email => email, :share_amount => amount.to_i)
    end
  end

  def website_host
    begin
      @website_url ||= URI.parse(self.website_url)
      @website_url.host
    rescue
      ""
    end
  end
  
  private
  
  def generate_uuid
    self.uuid = UUID.new.generate(:compact)
  end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  include ActiveMerchant::Billing::Integrations
  
  skip_before_filter :authenticate_if_staging, :only => :demo
  skip_before_filter :show_placeholder_if_production, :only => [ :coming_soon, :demo ]
  
  def coming_soon
  end
  
  def demo
    user = User.find_by_email('dev@25c.com')
    if user and user.buttons[0]
      @uuid = User.find_by_email('dev@25c.com').buttons[0].uuid
    end
  end
  
  def index
    if self.current_user
      redirect_to publisher_dashboard_path if self.current_user.role == 'publisher'
      redirect_to tipper_dashboard_path if self.current_user.role == 'tipper'
    end
  end

  # static pages
  def privacy
  end

  def faq
  end

  def terms
  end
  
  def about
  end
  
  def not_found
    render "not_found", :status => 404
  end
    
  def blog_header
    render :layout => "blank"
  end
  
  def blog_footer
    render :layout => "blank"
  end

end

app/views/home/buttons/_share_revenue.haml
#share-revenue.step-container
  .step-number 4
  .step-content
    %h3.step-title= t('home.buttons.receive_pledges.share_revenue_title')
    .step-body
      - if @button.share_users.blank?
        - invites = @button.invites.where(:state => Invite::State::OPEN)
        - if invites.empty?
          %span= t('home.buttons.receive_pledges.share_amount')
          %select#share-amount{ :type => 'text', :name => 'button[share_amount]' }
            - ['10', '20', '30', '40', '50', '60', '70', '80', '90'].each do |amount|
              %option{ :value => amount } #{amount}%
          %span= t('home.buttons.receive_pledges.share_email')
          %input#share-email{ :type => 'text', :name => 'button[share_email]', :value => t('home.buttons.receive_pledges.default_email')}
          / %p= t('home.buttons.receive_pledges.share_email_description')
          .clear
          #set-share-info.clear.btn.btn-strong{:disabled => 'disabled'}
            = t('home.buttons.receive_pledges.share_confirm')
        - else
          %p= t '.outstanding_invites'
          %table.table.table-striped
            %thead
              %tr
                %th= Invite.human_attribute_name(:share_amount)
                %th= Invite.human_attribute_name(:email)
                %th= Invite.human_attribute_name(:created_at)
                %th
            - invites.where(:state => Invite::State::OPEN).each do |invite|
              %tr
                %td= number_to_percentage(invite.share_amount, :precision => 0)
                %td= invite.email
                %td= l invite.created_at, :format => :date_only
                %td= link_to t('.cancel'), home_cancel_email_path(:invite_uuid => invite.uuid), :class => 'cancel-share-email', :remote => true, :method => :delete, :'data-type' => :json
      - else
        %p= t '.sharing'
        %ul.unstyled
          - @button.share_users.each do |share|
            - user = User.find_by_id(share['user'])
            %li
              = image_tag user.picture.url(:thumb)
              = user.display_name
              (#{number_to_percentage(share['share_amount'], :precision => 0)})
              &nbsp;&nbsp;
              = link_to t('.stop'), home_stop_share_path, :class => 'stop-share', :remote => true, :method => :delete, :'data-type' => :json
  .clear