config/routes.rb
Web25c::Application.routes.draw do
  
  # root :to => 'home#index'
  root :to => 'home#index'
  
  match 'coming_soon' => 'home#coming_soon', :as => :coming_soon
  
  # temporary demo page
  match 'demo' => 'home#demo'

  match 'auth/dwolla/callback' => 'home/payout#index', :as => :dwolla_auth_callback
  
  match 'sign-up' => 'users#new', :via => :get, :as => :register
  match 'sign-up' => 'users#create', :via => :post

  match 'sign-in' => 'sessions#new', :as => :sign_in, :via => :get
  match 'sign-in' => 'sessions#create', :via => :post
  match 'sign-out' => 'sessions#destroy', :as => :sign_out
  match 'request-password' => 'sessions#request_password', :as => :request_password
  match 'reset-password/:id' => 'sessions#reset_password', :as => :reset_password
  match 'auth/:provider/callback' => 'sessions#create'
  
  match 'widget/sign-in' => 'sessions#widget_new', :as => :widget_sign_in, :via => :get
  
  match 'about' => 'home#about', :as => :about
  match 'faq' => 'home#faq', :as => :faq
  match 'terms' => 'home#terms', :as => :terms
  match 'privacy' => 'home#privacy', :as => :privacy
  
  match 'blog/header' => 'home#blog_header', :as => :blog_header
  match 'blog/footer' => 'home#blog_footer', :as => :blog_footer
  
  # endpoints for Facebook Open Graph links
  match 'notes/:uuid' => 'open_graph#note', :as => :note
  match 'webpages/:uuid' => 'open_graph#webpage', :as => :webpage
  
  resources :i, :controller => 'invites', :as => 'invites', :only => [ :index, :show, :update ]
  
  namespace :tipper do
  
    # Dashboard
    match '' => 'dashboard#index', :as => :dashboard
    match 'cancel' => 'dashboard#cancel_click', :as => :cancel_click, :via => :delete
    
    # Buy Points
    match 'points' => 'points#index', :as => :points
    match 'points/checkout' => 'points#checkout', :as => :points_checkout
    match 'points/remove-card' => 'points#remove_card', :as => :points_remove_card
    
    # Payment
    match 'payment' => 'payment#index', :as => :payment
    match 'tip_register' => 'payment#tip_register', :as => :tip_register
    match 'site_register' => 'payment#site_register', :as => :site_register
    match 'payment/success' => 'payment#payment_success', :as => :payment_success
    match 'payment/failure' => 'payment#payment_failure', :as => :payment_failure
    match 'payment/dwolla'  => 'payment#payment_dwolla', :as => :payment_dwolla
    match 'create_payment' => 'payment#create_payment', :as => :create_payment, :via => :post
    
    # Account
    match 'account' => 'account#edit', :as => :account, :via => :get
    
  end
  
  namespace :publisher do
    # Dashboard
    root :to => 'dashboard#index', :as => :dashboard
    match 'request_payout' => 'dashboard#request_payout'
    match 'submit_request' =>  'dashboard#submit_request', :as => :submit_request
    # Widgets
    resources :widgets, :as => :buttons, :except => [ :new, :edit ]
    # Account
    resource :account, :as => :user, :only => [ :show, :update ]
    
    # Revenue Sharing
    match 'share_email' => 'widgets#share_email', :as => :share_email, :via => :put
    match 'cancel_email' => 'widgets#cancel_email', :as => :cancel_email, :via => :delete
    match 'stop_share' => 'widgets#stop_share', :as => :stop_share, :via => :delete    
  end
  
  namespace :admin do
    resources :users, :except => [ :new, :create ]
    match '' => 'dashboard#index', :as => :dashboard
    match 'process_payment' => 'dashboard#process_payment', :as => :process_payment, :via => :post
    match 'test' => 'dashboard#test', :as => :test
  end
  
  # catch-all 404 page for unknown routes
  match '*a' => 'home#not_found', :as => :not_found

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  include ActiveMerchant::Billing::Integrations
  
  skip_before_filter :authenticate_if_staging, :only => :demo
  skip_before_filter :show_placeholder_if_production, :only => [ :coming_soon, :demo ]
  
  def coming_soon
  end
  
  def demo
    user = User.find_by_email('dev@25c.com')
    if user and user.buttons[0]
      @uuid = User.find_by_email('dev@25c.com').buttons[0].uuid
    end
  end
  
  def index
    if self.current_user
      redirect_to publisher_dashboard_path if self.current_user.role == 'publisher'
      redirect_to tipper_dashboard_path if self.current_user.role == 'tipper'
    end
  end

  # static pages
  def privacy
  end

  def faq
  end

  def terms
  end
  
  def about
  end
  
  def not_found
    render "not_found", :status => 404
  end
    
  def blog_header
    render :layout => "blank"
  end
  
  def blog_footer
    render :layout => "blank"
  end

end

app/views/home/about.html.haml
- content_for :title, "About 25c Inc"

.row
  .span5
    .split-left
      %h2 Contact
      %p The best way to reach us is via email to <b>hello@25c.com</b>.
      %p We read every email even though we may not always be able to answer.
      %p <b>Address:</b>
      %p
        25c Inc.<br />
        660 York St<br />
        San Francisco, CA 94110<br />
        (415) 745-2605

  .span11
    .split-right
      %h2 About 25c Inc.
      %p 25c offers widgets that publishers can embed into their website to engage their fans and turn them into direct sponsors.  In a fun way.
      %p Advertising is a good source of income if one's creations attract millions of viewers. But what about the millions of niche content creators whose sites only attract 10,000 people? 25c provides a new solution by enabling fans to directly sponsor the content they love with a bit of their own money – even as little as 25 cents. 
      The result: content creators get paid and fans get more high-quality content. 
      
      %p
      %p
      
      %p 25c Inc. is a privately held company located in San Francisco, California.  Founded in 2013 by Internet veterans, the company operates the 25c.com service and owns a rapidly growing portfolio of patents, including promoted commenting and other mechanisms for publishers to increase revenue.

app/views/home/blog_footer.html.haml
- content_for :title, t('.title')


= content_for(:head) do
  %base{:target => "_parent"}
  :css
    body {
      padding-top: 0;
      padding-bottom: 0;
    }
    footer#footer-container{
      padding: 10px 40px 0 40px;
    }
    
%body{:style => "background-image: none; background-color: transparent;"}
  = render 'layouts/footer'

app/views/home/blog_header.html.haml
- content_for :title, t('.title')
- content_for :meta_description, t('.meta_description')

= content_for(:head) do
  %base{:target => "_parent"}
%body{:style => "background-image: none; background-color: transparent;"}
  = render 'layouts/header'
  = javascript_include_tag "application"

app/views/home/coming_soon.html.haml
= content_for(:head) do
  :css
    .brand {display: none !important;}
    ul.nav.pull-right {display: none !important;}
    footer.footer > .footer-inner > ul.pull-left {display: none !important;}

.padded
  .center
    = image_tag '25c-logo-canonical.png',
      :style => "width:360px;min-height:253px;margin:60px 0 40px 0"
    %h1{:style => "margin:0 0 60px 0"} Big changes are coming.

app/views/home/demo.html.haml
- content_for :title, '25c - Demo'

.padded

  %div{:style => 'margin:0 auto 40px auto;'}
    %h1 25c Notes Widget Demo
    %p Welcome to 25c! Below is a demo of the Notes Widget with placeholder data. Try it out!
    %p You can see this widget in the context of a Wired article here:
    %p= link_to "http://#{ENV['API25C_URL']}/public/test/wired-notes.html#25c",
      "http://#{ENV['API25C_URL']}/public/test/wired-notes.html#25c", :target => '_blank'

  %center.buffer
    #test-javascript
      %div{ :id => '25c',
        :width => 650,
        :class => "tip-25c-feed",
        :'data-id' => @uuid ? @uuid : '999',
        :'data-title' => '25c',
        :'data-url' => 'http://www.25c.com',
        :'data-demo' => @uuid ? 'false' : 'true'}
      :javascript
        !function(d,s,id){
          var js,fjs=d.getElementsByTagName(s)[0];
          if(!d.getElementById(id)){
            js=d.createElement(s);js.id=id;
            js.src="//#{ENV["API25C_URL"]}/public/javascripts/widget.js";
            fjs.parentNode.insertBefore(js,fjs);
          }
        } (document,"script","tip-25c-widget-js");

app/views/home/faq.html.haml
.padded
  
  %h1 Frequently Asked Questions

  %h2 What does 25c do?

  %p 25c offers widgets that publishers can use to turn fans into sponsors. 
  %p
  %p Widgets allow fans to directly sponsor content they like by giving 25c points -- and be seen and heard more than other users.
  %p
  %p Through the 25c point system, our widgets make it easy to give amounts as small as 25 cents or as large as $100 without requiring a separate credit card charge for every pledge.
  %p
  %p Our widgets incorporate lessons learned from Internet casual gaming.  In order to encourage participation, top sponsors are featured with their photo.  Top sponsors may also leave a brief note with their donation (if the publisher opts for this feature).  Sponsors are also notified when others give more, encouraging them to continue to donate.
  %p
  %p Best of all, the 25c widgets are FREE.  There are no up-front and no monthly expenses..  Revenue is shared 85%/15% much like on Google AdSense and the contributions are paid directly into your checking account.  
  %p
  %pBut unlike Google AdSense, which places unrelated third-party advertisers on your site, the 25c widget shows your very own fans.
  %p
  %p
  %hr
  %p
  
  %h2 How does it work?
  
  %p Each 25c point is worth 25 cents. Every new user receives 10 points upfront, equivalent to $2.50.  This allows users to give the widget a try at no cost.No user registration is required other than a Facebook login.  The Facebook login is used only for authenticating and uniquely identifying users who decided to become sponsors. Once users have logged in, they can assign points to content they like. 
  %p
  %p The 25c widget is typically inserted on a web page below the content of an article and above the user commenting system. It displays who the top sponsors are and allows users to give tips as small as 25 cents simply by clicking the 'Give' button.
  %p
  %p When a user wants to give more points than they have, they may purchase a pack of additional points and give those across the participating sites.
  %p
  %p There are no monthly or recurring charges to users.  Users fully control the pace that they give Based on what they truly value and enjoy.  Without being on any schedule.
  %p
  %hr
  %p
  
  %h2 What is the 25c point system about?
  
  %p In order to make it as easy as possible for your fans to give, our widgets are based on a point system:  Users purchase packs of points once and then can give those points to any participating website with much less overhead than is involved in charging a credit card. Every user receives 10 points up-front so they can try out the widget functionality immediately.  Users can then buy additional points or receive them as a reward. 
  %p
  %p The purchase of points is non-refundable as per our Terms of Service.
  %p
  %hr
  %p

  %h2 How does the 25c widget related to my user commenting system?

  %p The 25c widget offers different functionality than  user commenting systems. Typically publishers install the 25c widget between the main content of a page and the user commenting system. The 25c widget is about sponsorship payments and "top fan" recognition.  It is not about discussion.  

  %p An analogy: In a museum, people mill around and chit chat about the exhibit. But the sponsors who made the exhibit possible are listed on a plaque. 25c seeks to honor and incentivize that type of sponsorship on the web.  

  %p Users may give anonymously as well on 25c.
  %p
  %hr
  %p

  %h2 As a publisher, how do I get paid?

  %p We share revenue with publishers who provide space for our widget: the publisher receives 85% while we take 15%. 
  %p The 25c widget is free to install with no monthly or up-front charges to website owners. We get paid only if you get paid. After embedding a 25c widget into your content, monitor your dashboard on 25c.com to track the revenue your widgets are generating. Connect your bank account to obtain your share of revenue through an ACH transfer directly into your bank account. Additionally, on sites that feature multiple authors, site owners can use 25c to share revenue with their content creators. 
 

app/views/home/fb_share_callback.html.haml
%body
  :javascript
    window.close();

app/views/home/fees.html.haml
.padded

  %h1 Fees and Payment

  %h2 Users, Sponsors
  %p There is no fee for giving points.
  %p When you buy additional 25c points, there is a charge to your credit card.
  
  %hr

  %h2 Creators, Publishers
  %p Once funded, a pledged 25c gift is eligible for pay-out.  You may request a pay-out at any time.
  %p The 25c processing fee is 25 percent of the gross amount.
  %p The usual consumer card fees apply and are also deducted from the pay-out amount.  For credit card processing, this is on the order of 3%.

app/views/home/index.html.haml
- content_for :title, t('.title')
- content_for :meta_description, t('.meta_description')

%h1= t '.tagline'
.row
  .span14.offset1
    .row
      .span9
        = image_tag 'home-screenshot.png'
      .span5
        %h2= t '.value_prop'
        = t '.description_html'
        = link_to t('.add_now'), register_path, :class => 'button'
        = image_tag 'home-callout.png', :class => 'callout'
    .works_with
      %hr
      %h2= t '.works_with'
      %ul.unstyled<
        %li.works_with_wordpress
          %span WordPress
        %li.works_with_drupal> 
          %span Drupal
        %li.works_with_tumblr> 
          %span Tumblr
        %li.works_with_blogger> 
          %span Blogger
        %li.works_with_html 
          %span HTML & CSS
      = link_to t('.get_started'), register_path, :class => 'button'    

app/views/home/not_found.html.haml
- content_for :title, '25c - ' + t('.title')

.padded
  %h1= t('.title')
  %p= raw t('.no_page_found', :path => request.fullpath, 
    :return_home => link_to(t('.return_home'), root_url))

app/views/home/privacy.html.haml
.padded
  
  %h1 Privacy Policy

  %p This policy describes the ways how 25c Inc. (“25c”, “we”, “us” or “our”) collect, store, use and protect your personal information. You accept this Privacy Policy when you sign up for or use our products, services or any other features, technologies or functionalities offered by us on our website, application or through any other means (collectively the “25c Services"). We may amend this policy at any time by posting a revised version on our website. The revised version will be effective at the time we post it. In addition, if the revised version includes a substantial change, we will provide you with 30 days’ prior notice by posting notice of the change on the "Policy Updates" page of our website.

  %hr

  %h2 How we collect information about you

  %p When you visit the 25c website or use the 25c Services, we collect information sent to us by your computer, mobile phone or other access device. This information may include your IP address, device information including but not limited to identifier, name and type, operating system, location, mobile network information and standard web log information, such as your browser type, traffic to and from our site and the pages you accessed on our website.

  %p If you open an account or use the 25c Services, we may collect the following types of information:

  %p Contact information - your name, address, phone, email, and other similar information. Financial information - the full bank account numbers and/or credit card numbers that you link to your 25c account or give us when you use the 25c Services.

  %p Before permitting you to use the 25c Services, we may require you to provide additional information we can use to verify your identity or address or manage risk, such as your date of birth, social security number or other information. We may also obtain information about you from third parties such as credit bureaus and identity verification services.

  %p When you use the 25c Services, we collect information about your transactions and your other activities on our website, application or when using the 25c Services and we may collect information about your computer or other access device for fraud prevention purposes.

  %p You may choose to provide us with access to certain personal information stored by third parties such as social media sites (such as Facebook and Twitter). The information we have access to varies by site and is controlled by your privacy settings on that site and your authorization. By associating an account managed by a third party with your 25c account and authorizing 25c to have access to this information, you agree that 25c may collect, store and use this information in accordance with this Privacy Policy.

  %p In order to help protect you from fraud and misuse of your personal information, we may collect information about your use and interaction with our website, application or the 25c Services. For example, we may evaluate your computer, mobile phone or other access device to identify any malicious software or activity that may affect the availability of the 25c Services.

  %p Finally, we may collect additional information from or about you in other ways such as contacts with our customer support team or results when you respond to a survey.

  %hr

  %h2 How we use cookies

  %p When you access our website or content or use our application or the 25c Services, we or companies we work with, may place small data files called cookies or pixel tags on your computer or other device. We use these technologies to recognize you as a 25c customer, customize the 25c Services, content and advertising, measure promotional effectiveness, collect information about your computer or other access device to mitigate risk, help prevent fraud and promote trust and safety.

  %p We use both session and persistent cookies when you access our website or content. Session cookies expire and no longer have any effect when you log out of your account or close your browser. Persistent cookies remain on your browser until you erase them or they expire.

  %p We encode our cookies so that only we can interpret the information stored in them. You are free to decline our cookies if your browser or browser add-on permits, but doing so may interfere with your use of our website. The help section of most browsers or browser add-ons provides instructions on blocking, deleting or disabling cookies.

  %hr

  %h2 How we protect and store personal information

  %p Throughout this policy, we use the term "personal information" to describe information that can be associated with a specific person and can be used to identify that person. We do not consider personal information to include information that has been anonymized so that it does not identify a specific user.

  %p We store and process your personal information on our computers in the US and elsewhere in the world where 25c facilities or our service providers are located, and we protect it by maintaining physical, electronic and procedural safeguards in compliance with applicable US federal and state regulations. We use computer safeguards such as firewalls and data encryption, we enforce physical access controls to our buildings and files, and we authorize access to personal information only for those employees who require it to fulfill their job responsibilities.

  %hr

  %h2 How we use the personal information we collect

  %p Our primary purpose in collecting personal information is to provide you with a secure, smooth, efficient, and customized experience. We may use your personal information to:

  %ul

    %li provide the 25c Services and customer support you request;

    %li process transactions and send notices about your transactions;

    %li resolve disputes, collect fees, and troubleshoot problems;

    %li prevent potentially prohibited or illegal activities, and enforce our User Agreement;

    %li customize, measure, and improve the 25c Services and the content and layout of our website and applications;

    %li deliver targeted marketing, service update notices, and promotional offers based on your communication preferences;

    %li compare information for accuracy and verify it with third parties.

  %hr

  %h2 Marketing

  %p We do not sell or rent your personal information to third parties for their marketing purposes. We may combine your information with information we collect from other companies and use it to improve and personalize the 25c Services, content and advertising. If you no longer wish to receive notifications from our service, you can adjust your preferences by visiting the user profile page of the application.

  %hr

  %h2 How we share personal information with other 25c users

  %p To process your donations, we may share some of your personal information with the person or company that you are donating to.
  
  %hr

  %h2 How we share personal information with other parties

  %p We may share your personal information with:

  %ul

    %li Service providers under contract who help with parts of our business operations such as fraud prevention, bill collection, marketing and technology services. Our contracts dictate that these service providers only use your information in connection with the services they perform for us and not for their own benefit.

    %li Financial institutions and credit bureaus to report account information, as permitted by law.

    %li Banking partners as required by credit card association rules for inclusion on their list of terminated merchants (in the event that you meet their criteria which includes having 25c close your 25c Account due to your breach of the 25c User Agreement).

    %li Companies that we plan to merge with or be acquired by. (Should such a combination occur, we will require that the new combined entity follow this privacy policy with respect to your personal information. If your personal information could be used contrary to this policy, you will receive prior notice.)

    %li Law enforcement, government officials, or other third parties when we are compelled to do so by a subpoena, court order or similar legal procedure we need to do so to comply with law or credit card rules

    %li we believe in good faith that the disclosure of personal information is necessary to prevent physical harm or financial loss, to report suspected illegal activity or to investigate violations of our User Agreement.

    %li Other third parties with your consent or direction to do so.

  %p 25c will not sell or rent any of your personal information to third parties for their marketing purposes and only shares your personal information with third parties as described in this policy.

  %p If you open a 25c account directly on a third party website or via a third party application, any information that you enter on that website or application (and not directly on a 25c website) will be shared with the owner of the third party website or application and your information may be subject to their privacy policies.

  %hr

  %h2 How you can access or change your personal information
  
  %p You can review and edit your personal information at any time by logging in to your account and going to the Profile page. You can also close your account through the 25c website. If you close your 25c account, we will mark your account in our database as "Inactive," but will keep your account information in our database. This is necessary in order to deter fraud, by ensuring that persons who try to commit fraud will not be able to avoid detection simply by closing their account and opening a new account. However, if you close your account, your personally identifiable information will not be used by us for any further purposes, nor sold or shared with third parties, except as necessary to prevent fraud and assist law enforcement, as required by law or in accordance with this Privacy Policy.
  
  %hr
  
  %h2 How you can contact us about privacy questions
  
  %p If you have questions or concerns regarding this policy, you should contact us at privacy@25c.com.