config/routes.rb
Web25c::Application.routes.draw do
  
  # root :to => 'home#index'
  root :to => 'home#index'
  
  match 'coming_soon' => 'home#coming_soon', :as => :coming_soon
  
  # temporary demo page
  match 'demo' => 'home#demo'

  match 'auth/dwolla/callback' => 'home/payout#index', :as => :dwolla_auth_callback
  
  match 'sign-up' => 'users#new', :via => :get, :as => :register
  match 'sign-up' => 'users#create', :via => :post

  match 'sign-in' => 'sessions#new', :as => :sign_in, :via => :get
  match 'sign-in' => 'sessions#create', :via => :post
  match 'sign-out' => 'sessions#destroy', :as => :sign_out
  match 'request-password' => 'sessions#request_password', :as => :request_password
  match 'reset-password/:id' => 'sessions#reset_password', :as => :reset_password
  match 'auth/:provider/callback' => 'sessions#create'
  
  match 'widget/sign-in' => 'sessions#widget_new', :as => :widget_sign_in, :via => :get
  
  match 'about' => 'home#about', :as => :about
  match 'faq' => 'home#faq', :as => :faq
  match 'terms' => 'home#terms', :as => :terms
  match 'privacy' => 'home#privacy', :as => :privacy
  
  match 'blog/header' => 'home#blog_header', :as => :blog_header
  match 'blog/footer' => 'home#blog_footer', :as => :blog_footer
  
  # endpoints for Facebook Open Graph links
  match 'notes/:uuid' => 'open_graph#note', :as => :note
  match 'webpages/:uuid' => 'open_graph#webpage', :as => :webpage
  
  resources :i, :controller => 'invites', :as => 'invites', :only => [ :index, :show, :update ]
  
  namespace :tipper do
  
    # Dashboard
    match '' => 'dashboard#index', :as => :dashboard
    match 'cancel' => 'dashboard#cancel_click', :as => :cancel_click, :via => :delete
    
    # Buy Points
    match 'points' => 'points#index', :as => :points
    match 'points/checkout' => 'points#checkout', :as => :points_checkout
    match 'points/remove-card' => 'points#remove_card', :as => :points_remove_card
    
    # Payment
    match 'payment' => 'payment#index', :as => :payment
    match 'tip_register' => 'payment#tip_register', :as => :tip_register
    match 'site_register' => 'payment#site_register', :as => :site_register
    match 'payment/success' => 'payment#payment_success', :as => :payment_success
    match 'payment/failure' => 'payment#payment_failure', :as => :payment_failure
    match 'payment/dwolla'  => 'payment#payment_dwolla', :as => :payment_dwolla
    match 'create_payment' => 'payment#create_payment', :as => :create_payment, :via => :post
    
    # Account
    match 'account' => 'account#edit', :as => :account, :via => :get
    
  end
  
  namespace :publisher do
    # Dashboard
    root :to => 'dashboard#index', :as => :dashboard
    match 'request_payout' => 'dashboard#request_payout'
    match 'submit_request' =>  'dashboard#submit_request', :as => :submit_request
    # Widgets
    resources :widgets, :as => :buttons, :except => [ :new, :edit ]
    # Account
    resource :account, :as => :user, :only => [ :show, :update ]
    
    # Revenue Sharing
    match 'share_email' => 'widgets#share_email', :as => :share_email, :via => :put
    match 'cancel_email' => 'widgets#cancel_email', :as => :cancel_email, :via => :delete
    match 'stop_share' => 'widgets#stop_share', :as => :stop_share, :via => :delete    
  end
  
  namespace :admin do
    resources :users, :except => [ :new, :create ]
    match '' => 'dashboard#index', :as => :dashboard
    match 'process_payment' => 'dashboard#process_payment', :as => :process_payment, :via => :post
    match 'test' => 'dashboard#test', :as => :test
  end
  
  # catch-all 404 page for unknown routes
  match '*a' => 'home#not_found', :as => :not_found

end

app/controllers/tipper/dashboard_controller.rb
class Tipper::DashboardController < Tipper::TipperController

  def index
    @clicks = self.current_user.clicks.where('amount>0').order('created_at DESC').page params[:page]
    render :partial => 'clicks' if request.xhr?
  end
  
  def cancel_click
    if self.current_user.clicks.find_by_uuid(params[:uuid]).cancel
      if request.xhr?
        head :ok
      else
        redirect_to tipper_dashboard_path, :notice => t('tipper.dashbaord.cancel_click.success')
      end
    else
      if request.xhr?
        render :text => t('tipper.dashboard.cancel_click.failure'), :status => :internal_server_error
      else
        redirect_to tipper_dashboard_path, :alert => t('tipper.dashboard.cancel_click.failure')
      end
    end
  end

end

app/controllers/tipper/payment_controller.rb
class Tipper::PaymentController < Tipper::TipperController
  
  skip_before_filter :verify_registration, :only => [:site_register, :tip_register]

  def index
    @user = current_user
    if request.method == 'POST'
      save_stripe_info(@user)
      render 'confirm_payment'
    end
  end
  
  def tip_register
    @user = current_user
    if request.method == 'POST'
      save_stripe_info(@user)
      render 'confirm_tip_register', :layout => 'popup'
    else
      render :layout => 'popup'
    end
  end
  
  def site_register
    @user = current_user
    if request.method == 'POST'
      save_stripe_info(@user)
      render 'confirm_site_register'
    end
  end
  
  def create_payment
    @user = current_user
    payment = @user.payments.create!({ :amount => @user.balance, :payment_type => 'payin' })
    respond_to do |format|
      format.json { render :json => { uuid: payment.uuid } }
      format.html { render :nothing => true, :status => 200, :content_type => 'text/html'}
    end
  end
  
  def payment_success

  end
  
  def payment_failure
    @user = current_user
  end
  
  private
  
  def save_stripe_info(user)
    Stripe.api_key = STRIPE_SETTINGS[:secret_key]

    # get the credit card details submitted by the form
    token = params[:stripeToken]
          
    user.editing = true
    
    if user.stripe_id.blank?
      # create a Customer
      customer = Stripe::Customer.create(:card => token, :description => @user.email)
      # save the customer ID
      user.stripe_id = customer.id
    else
      customer = Stripe::Customer.retrieve(user.stripe_id)
      customer.card = token
      customer.save
    end
        
    user.stripe_last4 = customer.active_card.last4
    user.has_valid_card = true
    user.is_suspended = false
    user.save!
    user.editing = false
    
  end
  
end

app/controllers/tipper/points_controller.rb
class Tipper::PointsController < Tipper::TipperController
  
  def index
    @payments = self.current_user.payments.order('created_at DESC').page params[:page]
    render :partial => 'payments' if request.xhr?
  end
  
  def remove_card
    begin
      customer = Stripe::Customer.retrieve(self.current_user.stripe_id)
      customer.delete
      self.current_user.editing = true
      self.current_user.stripe_id = nil
      self.current_user.stripe_type = nil
      self.current_user.stripe_exp_month = nil
      self.current_user.stripe_exp_year = nil
      self.current_user.has_valid_card = nil
      self.current_user.save!
      redirect_to tipper_points_path, :notice => t('tipper.points.remove_card.success')
    rescue => e
      redirect_to tipper_points_path, :alert => e.to_s
    end
  end
  
  def checkout
    @amount_points = params[:amount].to_i
    redirect_to tipper_points_path, :alert => t('tipper.points.checkout.invalid_amount') unless [ 20, 45, 100, 300, 700 ].include?(@amount_points)    
    @amount_values = {
      20 => 500,
      45 => 1000,
      100 => 2000,
      300 => 5000,
      700 => 10000
    }    
    if request.method == 'POST'
      begin
        token = params[:stripe_token]
        unless params[:save].nil? or token.nil?
          # save card info into customer object
          if self.current_user.stripe_id.blank?
            # create a Customer
            customer = Stripe::Customer.create(:card => token, :description => "#{self.current_user.uuid} (#{self.current_user.email})")
            self.current_user.stripe_id = customer.id
          else
            customer = Stripe::Customer.retrieve(self.current_user.stripe_id)
            customer.card = token
            customer.description = "#{self.current_user.uuid} (#{self.current_user.email})"
            customer.save
          end
          # save display info
          self.current_user.editing = true
          self.current_user.stripe_last4 = customer.active_card.last4
          self.current_user.stripe_type = customer.active_card.type
          self.current_user.stripe_exp_month = customer.active_card.exp_month
          self.current_user.stripe_exp_year = customer.active_card.exp_year
          self.current_user.has_valid_card = true
          self.current_user.save!
        end
        # charge card
        charge = {
          :amount => @amount_values[@amount_points],
          :currency => 'usd',
          :description => "#{@amount_points} points for #{self.current_user.uuid} (#{self.current_user.email})"
        }
        if self.current_user.stripe_id.blank?
          charge[:card] = token
        else
          charge[:customer] = self.current_user.stripe_id
        end
        self.current_user.with_lock do
          charge = Stripe::Charge.create(charge)
          self.current_user.balance_paid += @amount_points
          self.current_user.save!
          payment = self.current_user.payments.build
          payment.transaction_id = charge.id
          payment.amount_points = @amount_points
          payment.amount_value = @amount_values[@amount_points]
          payment.currency = 'usd'
          payment.save!
        end
        redirect_to tipper_points_path, :notice => t('tipper.points.checkout.success')
        return
      rescue Stripe::CardError => e
        # Since it's a decline, Stripe::CardError will be caught
        body = e.json_body
        err  = body['error']

        puts "Status is: #{e.http_status}"
        puts "Type is: #{err['type']}"
        puts "Code is: #{err['code']}"
        # param is '' in this case
        puts "Param is: #{err['param']}"
        puts "Message is: #{err['message']}"
      rescue Stripe::InvalidRequestError => e
        # Invalid parameters were supplied to Stripe's API
      rescue Stripe::AuthenticationError => e
        # Authentication with Stripe's API failed
        # (maybe you changed API keys recently)
      rescue Stripe::APIConnectionError => e
        # Network communication with Stripe failed
      rescue Stripe::StripeError => e
        # Display a very generic error to the user, and maybe send
        # yourself an email
      rescue => e
        # Something else happened, completely unrelated to Stripe
      end      
      redirect_to tipper_points_path, :alert => e.to_s
    end
  end
  
end

app/controllers/tipper/tipper_controller.rb
class Tipper::TipperController < ApplicationController
  before_filter :require_tipper

end

app/views/tipper/points/_payments.html.haml
- @payments.each do |payment|
  %tr
    %td.col-date= l payment.created_at, :format => :date_short
    %td.col-amount= payment.amount_points
    %td.col-amount-value= number_to_currency payment.amount_value/100.0
    %td.col-action &nbsp;
- unless @payments.last_page?
  %tr
    %td{ :colspan => 5}
      = link_to_next_page @payments, t('.show_more'), :class => 'payment-show-more', :remote => true

app/views/tipper/points/checkout.html.haml
- content_for :title, t('.title')

= content_for(:js) do
  = javascript_include_tag "https://js.stripe.com/v1/"
  :javascript
    Stripe.setPublishableKey('#{STRIPE_SETTINGS[:publishable_key]}');
    $(document).ready(function() {
      $("#payment-form").submit(function(event) {
        $('.submit-button').attr("disabled", "disabled");
        Stripe.createToken({
          number: $('#card-number').val(),
          cvc: $('#card-cvc').val(),
          exp_month: $('#card-expiry-month').val(),
          exp_year: $('#card-expiry-year').val()
        }, stripeResponseHandler);
        return false;
      });
      $(".use_new_card").on('click', function(event) {
        $('.checkout_saved_card').hide();
        $('.checkout_new_card').show();
        return false;
      });
      
      function stripeResponseHandler(status, response) {
        if (response.error) {
          $(".payment-errors").text(response.error.message + '.').show();
          $(".submit-button").removeAttr("disabled");
        } else {
          var $form = $("#payment-form");
          var token = response['id'];
          $form.append("<input type='hidden' name='stripe_token' value='" + token + "'/>");
          $form.get(0).submit();
        }
      }
    });

.padded
  %h1= yield :title
  %p Congratulations #{current_user.display_name}! You've decided to buy #{@amount_points} points for #{number_to_currency(@amount_values[@amount_points].to_f / 100.0)}. 
  %p.buffer Please enter your payment information now so you can start rewarding content you love!
.row
  .span3
    .points
      = image_tag "points-#{@amount_points}.png"
      %br
      = number_to_currency(@amount_values[@amount_points].to_f / 100.0)
  .span12
    - if self.current_user.has_valid_card
      .checkout_saved_card
        = form_tag tipper_points_checkout_path do
          = hidden_field_tag :amount, @amount_points
          .control-group
            %h2= t '.use_saved_card'
            %p 
              #{current_user.stripe_type} **** **** **** #{current_user.stripe_last4}
              %br
              = t '.expires', :expiration => "#{current_user.stripe_exp_month}/#{current_user.stripe_exp_year}"
            %p= t '.or_html', :use_new_card => link_to(t('.use_new_card'), '#', :class => 'use_new_card')
          = submit_tag t('.pay_now'), :class => 'button'
    .checkout_new_card{ :style => "display:#{self.current_user.has_valid_card ? 'none' : 'block'}"}
      = form_tag tipper_points_checkout_path, :id => 'payment-form' do
        = hidden_field_tag :amount, @amount_points
        .payment-errors.alert.alert-error.buffer.hide
        .control-group
          = label_tag 'card-number', t('.card_number')
          .controls
            = text_field_tag 'card-number', nil, :name => nil, :size => "20", :autocomplete => "off"
        .control-group
          = label_tag 'card-cvc', t('.card_cvc')
          .controls
            = text_field_tag 'card-cvc', nil, :name => nil, :size => "4", :autocomplete => "off"
        .control-group
          = label_tag 'card-expiry-month', t('.expiration')
          .controls
            = select_tag 'card-expiry-month', options_for_select((1..12).map{|m| "%02d"%m }), :name => nil
            = select_tag 'card-expiry-year', options_for_select((Time.now.year..Time.now.year+10)), :name => nil
        .control-group
          = label_tag 'save', :class => 'checkbox' do
            = check_box_tag 'save', 1, true
            = t '.card_save'
        = submit_tag t('.pay_now'), :class => 'button submit-button'

app/views/tipper/points/index.html.haml
.buy-points
  %h2= t '.buy_points'
  .row
    .span11
      %ul.buy-points<
        %li
          = link_to tipper_points_checkout_path(:amount => 20), :class => 'buy-points-20' do
            %span= t '.points_20'
          $5.00
        %li>
          = link_to tipper_points_checkout_path(:amount => 45), :class => 'buy-points-45' do
            %span= t '.points_45'
          $10.00
        %li>
          = link_to tipper_points_checkout_path(:amount => 100), :class => 'buy-points-100' do
            %span= t '.points_100'
          $20.00
        %li>
          = link_to tipper_points_checkout_path(:amount => 300), :class => 'buy-points-300' do
            %span= t '.points_300'
          $50.00
        %li
          = link_to tipper_points_checkout_path(:amount => 700), :class => 'buy-points-700' do
            %span= t '.points_700'
          $100
    .span5
      .split-left
        = t '.about_html'
  %hr
.row
  .span5
    .split-left
      %h2
        = t '.current_balance', :balance => current_user.balance
      - if current_user.has_valid_card
        %h2= t '.current_payment'
        .credit_card
          #{current_user.stripe_type} **** **** **** #{current_user.stripe_last4}
          %span
            = t '.expires', :expiration => "#{current_user.stripe_exp_month}/#{current_user.stripe_exp_year}"
            (#{link_to t('.remove'), tipper_points_remove_card_path})
  .span11
    .split-right
      %h2= t '.purchase_history'
      %table
        %thead
          %tr
            %th.col-date= Payment.human_attribute_name(:created_at)
            %th.col-amount= Payment.human_attribute_name(:amount_points)
            %th.col-amount-value= Payment.human_attribute_name(:amount_value)
            %th.col-action &nbsp;
        %tbody
          = render :partial => 'payments'